# Conexión API extracción datos metereológicos

In [4]:
import pyowm
import json
import pandas as pd

from datetime import datetime

In [5]:
KEY = '16247b8439d1a62601d38844971ccccc'
owm = pyowm.OWM(KEY)
obs = owm.weather_at_place('Gandia, ES')

In [6]:
columns = [
    "reception_time", "Location_name", "Location_lon", "Location_lat",
    "ID", "country",
    "reference_time", "sunset_time", "sunrise_time", "clouds", "rain",
    "wind_speed", "wind_deg", "humidity", "pressure", "sea_level", 
    "temp", "temp_kf", "temp_max", "temp_min", "status", "detailed_status", 
    "weather_code", "weather_icon_name", "visibility_distance", "dewpoint", 
    "humidex", "heat_index"
]
data_read = pd.DataFrame(columns=columns)

In [7]:
def get_data(obs):
    
    data = json.loads(obs.to_JSON())

    return {
    "reception_time" : datetime.fromtimestamp(data["reception_time"]),
    "Location_name" : data["Location"]["name"], 
    "Location_lon" : data["Location"]["coordinates"]["lon"], 
    "Location_lat" : data["Location"]["coordinates"]["lat"],
    "ID" : data["Location"]["ID"], 
    "country" : data["Location"]["country"],
        
    "reference_time" : datetime.fromtimestamp(data["Weather"]["reference_time"]),
    "sunset_time" : datetime.fromtimestamp(data["Weather"]["sunset_time"]),
    "sunrise_time" : datetime.fromtimestamp(data["Weather"]["sunrise_time"]),

    "clouds" : data["Weather"]["clouds"],
    "rain" : data["Weather"]["rain"],

    "wind_speed" : data["Weather"]["wind"]["speed"],
    "wind_deg" : data["Weather"]["wind"]["deg"],

    "humidity" : data["Weather"]["humidity"],

    "pressure" : data["Weather"]["pressure"]["press"],
    "sea_level" : data["Weather"]["pressure"]["sea_level"],

    "temp" : data["Weather"]["temperature"]["temp"],
    "temp_kf" : data["Weather"]["temperature"]["temp_kf"],
    "temp_max" : data["Weather"]["temperature"]["temp_max"],
    "temp_min" : data["Weather"]["temperature"]["temp_min"],

    "status" : data["Weather"]["status"],
    "detailed_status" : data["Weather"]["detailed_status"],
    "weather_code" : data["Weather"]["weather_code"],
    "weather_icon_name" : data["Weather"]["weather_icon_name"],

    "visibility_distance" : data["Weather"]["visibility_distance"],
    "dewpoint" : data["Weather"]["dewpoint"],
    "humidex" : data["Weather"]["humidex"],
    "heat_index" : data["Weather"]["heat_index"]
    }

In [8]:
def database(obs, data_read):
    return data_read.append(pd.Series(get_data(obs)), ignore_index=True)

In [11]:
data_read = database(obs, data_read)
data_read.tail(5)

,reception_time,Location_name,Location_lon,Location_lat,ID,country,reference_time,sunset_time,sunrise_time,clouds,...,temp_max,temp_min,status,detailed_status,weather_code,weather_icon_name,visibility_distance,dewpoint,humidex,heat_index
0,2020-09-23 18:59:16,Gandia,-0.18,38.97,2517367,ES,2020-09-23 18:59:00,2020-09-23 19:56:27,2020-09-23 07:49:32,83,...,300.37,300.37,Clouds,broken clouds,803,04d,10000,None,None,None
1,2020-09-23 18:59:16,Gandia,-0.18,38.97,2517367,ES,2020-09-23 18:59:00,2020-09-23 19:56:27,2020-09-23 07:49:32,83,...,300.37,300.37,Clouds,broken clouds,803,04d,10000,None,None,None
2,2020-09-23 18:59:16,Gandia,-0.18,38.97,2517367,ES,2020-09-23 18:59:00,2020-09-23 19:56:27,2020-09-23 07:49:32,83,...,300.37,300.37,Clouds,broken clouds,803,04d,10000,None,None,None

In [12]:
data_read.head(1).T

                                       0
reception_time       2020-09-23 18:59:16
Location_name                     Gandia
Location_lon                       -0.18
Location_lat                       38.97
ID                               2517367
country                               ES
reference_time       2020-09-23 18:59:00
sunset_time          2020-09-23 19:56:27
sunrise_time         2020-09-23 07:49:32
clouds                                83
rain                                  {}
wind_speed                          0.89
wind_deg                             270
humidity                               6
pressure                            1008
sea_level                           None
temp                              300.37
temp_kf                             None
temp_max                          300.37
temp_min                          300.37
status                            Clouds
detailed_status            broken clouds
weather_code                         803
weather_icon_name                    04d
visibility_distance                10000
dewpoint                            None
humidex                             None
heat_index                          None